baseURL = 'https://alpsy-informatik.uibk.ac.at/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true


[languages]
  [languages.en]
    title = "ALPSY 2025"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/alpsy-logo-2025.png"
  description = "Algebraic Aspects in the Design and Cryptanalysis of Modern Symmetric Cryptography"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  recent_posts_number = 0